/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  Buyer,
  BuyerInterface,
} from "../../../contracts/MarketPlace.sol/Buyer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "artID",
        type: "uint256",
      },
    ],
    name: "buyArt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061018c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063fc7a900b14610030575b600080fd5b61004a600480360381019061004591906100b2565b61004c565b005b600080828152602001908152602001600020600081548092919061006f9061010e565b919050555050565b600080fd5b6000819050919050565b61008f8161007c565b811461009a57600080fd5b50565b6000813590506100ac81610086565b92915050565b6000602082840312156100c8576100c7610077565b5b60006100d68482850161009d565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006101198261007c565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff820361014b5761014a6100df565b5b60018201905091905056fea2646970667358221220e692c92a5e7405bcabe424d1cfd0e3f825e3b2284a12f35cde4ef8a61c4352d164736f6c63430008120033";

type BuyerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BuyerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Buyer__factory extends ContractFactory {
  constructor(...args: BuyerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Buyer> {
    return super.deploy(overrides || {}) as Promise<Buyer>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Buyer {
    return super.attach(address) as Buyer;
  }
  override connect(signer: Signer): Buyer__factory {
    return super.connect(signer) as Buyer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BuyerInterface {
    return new utils.Interface(_abi) as BuyerInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Buyer {
    return new Contract(address, _abi, signerOrProvider) as Buyer;
  }
}
